name: ai_mini_games
description: AI-powered mini games platform
version: 1.0.0+1

environment:
  sdk: ^3.9.0
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
    
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod: ^2.4.9
  
  # Navigation
  go_router: ^12.1.3
  
  # Network
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  
  # UI Components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  
  # Games
  flame: ^1.15.0
  
  # Analytics & Monitoring
  firebase_core: ^2.24.2
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.8
  sentry_flutter: ^7.14.0
  
  # Authentication
  crypto: ^3.0.3
  jwt_decode: ^0.3.1
  
  # Utils
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  intl: ^0.19.0
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  
  # Testing
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true